### ISSUE TITLE
We tried to install it but it doesn't show up in themes.

### ISSUE THREAD

**Issue by JohnMcLear** [rpc-scandinavia/kopano-web-client-night-theme#1]
Symlinks to folders are there.

Any other steps required?

**Comment by rpc-scandinavia** [comment]
Forget the symlinks, I just use them so it is easy to develop.

Delete the symlinks, and copy the contents of folder "plugins" to "/usr/share/kopano-webapp/plugins", and the contents of folder "iconsets" to "/usr/share/kopano-webapp/client/resources/iconsets".

Make sure that the security on the copied files are the same as your "kopano-webapp" folder. I would guess that is is something like the "www-data" user.

**Comment by JohnMcLear** [comment]
Sorry I should have said that we tried this but nothing worked ;\  No errors/no problems, just didn;t work :(  Probably our fault!

**Comment by rpc-scandinavia** [comment]
Thanks for writing.

That is strange, it is just files that needs to be copied. My project contains other stuff, to develop the theme and change the colours in the SVG images.

After you originally wrote, I updated the GitHub page with the installation instructions - have you tried the newest download, and without using any of the scripts ?
